Facenovel/config/routes.rb
Facenovel::Application.routes.draw do
  devise_for :users
  resources :statuses
  root to: 'statuses#index'

  

end

Facenovel/app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
end

Facenovel/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name,	presence: true, 
  							uniqueness: true,
  							format: {with: /a-zA-Z0-9_-/, message: 'Must be formatted correctly.'}
  
  def full_name
  	first_name + ' ' + last_name
  end
end

Facenovel/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :profile_name]
  end

end

Facenovel/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:content, :user_id)
    end
end

Facenovel/app/helpers/application_helper.rb
module ApplicationHelper
end

Facenovel/app/helpers/statuses_helper.rb
module StatusesHelper
end

Facenovel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facenovel</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      			<span class="sr-only">Toggle navigation</span>
	      			<span class="icon-bar"></span>
	      			<span class="icon-bar"></span>
	      			<span class="icon-bar"></span>
	    		</button>
	    		<a class="navbar-brand" href="#">Facenovel</a>
	    	</div>

	    	<div class="collapse navbar-collapse navbar-ex1-collapse">
    			<ul class="nav navbar-nav">
      				<li><%= link_to "All Statuses", statuses_path %></li>
      			</ul>

      			<ul class="nav navbar-nav navbar-right">
      				<% if user_signed_in? %>
      					<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
      					<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      				<% else %>
      					<li><%= link_to "Register", new_user_registration_path %></li>
      					<li><%= link_to "Sign In", new_user_session_path %></li>
      				<% end %>
      			</ul>
      		</div>
    	</div>

	</nav>

	<div class="container">
		<p class="notice"><%= notice %></p>
    	<p class="alert"><%= alert %></p>

		<%= yield %>
	</div>

</body>
</html>

Facenovel/app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: 'form-horizontal'}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <%= f.button :submit %>

<% end %>

Facenovel/app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

Facenovel/app/views/statuses/index.html.erb
<div class="page-header">
  <h1>Live Feed</h1>
</div>

<%= link_to "Post a new status", new_status_path, class: "btn btn-primary" %>

<% @statuses.each do |status| %>

<div class="status">

  <strong><%= status.user.full_name %></strong>
  <p><%= status.content %></p>
  <div class="meta">
    <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
    <span class="admin">
      | <%= link_to "Edit", edit_status_path(status) %> |
      <%= link_to "Delete", status, method: :delete, data: {confirm: "Are you sure you want to delete this status?" } %>
    </span>
  </div>

</div>

<% end %>

Facenovel/app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

Facenovel/app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>